name: Sync Fork

on:
  workflow_dispatch:
    types:
      - fork-syncer
  # schedule:
  #   - cron: '*/30 * * * *' # every 30 minutes

jobs:
  sync:
    runs-on: fork-syncer-runner
    steps:
    - uses: actions/checkout@v2
    - name: Sync upstream forks
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        REPO_OWNER: mathew-fleisch
      run: |
        if ! [ -f "forks" ]; then
          echo "No forks file found"
          exit 1
        fi
        if ! [ -f "sync.sh" ]; then
          echo "sync.sh script missing"
          exit 1
        fi
        while read -r line; do
          echo "Syncing $line -> $REPO_OWNER"
          ./sync.sh $REPO_OWNER $line
        done < forks